config/routes.rb
BakingJournal::Application.routes.draw do
  
  resources :entries do
    collection do
      delete 'destroy_multiple'
    end
  end
  

  resources :users

  root :to => 'entries#index'
  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  has_many :entry_ingredients
  has_many :ingredients, :through => :entry_ingredients
  has_many :steps
  
  before_save :default_name, :if => lambda { |e| e[:name].blank? }
  
  accepts_nested_attributes_for :entry_ingredients, :allow_destroy => true
  accepts_nested_attributes_for :steps, :reject_if => lambda { |s| s[:description].blank? }, :allow_destroy => true
  
  def default_name
      self.name = Time.new
  end
  
  #calculate bakers percentage of entry
  def calc_bakers_percentages
    #flour is the base, always 100%
    #other ingredients will be calculated as a percentage of the flour weight
    #bakers percent(ingredient) = 100% *ingredient_mass/flour_mass
    #    
    for e in self.ingredients
      if e.name == "flour"
      end
    end
  end
  
  #Calculate hydration percentage of dough  
  def calc_hydration
    #Percentage of water to flour
    
    #TODO sum percentage of all liquids in bakers percentage, if the bakers percentage calc fails, use only the flour and liquids

  end
  
end

app/models/entry_ingredient.rb
class EntryIngredient < ActiveRecord::Base
  belongs_to :entry
  belongs_to :ingredient
  belongs_to :unit

  accepts_nested_attributes_for :ingredient, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :entry_ingredients
  has_many :entries, :through => :entry_ingredients
  
end

app/models/step.rb
class Step < ActiveRecord::Base
  #has_many :images
  belongs_to :entry
  attr_accessible :description, :entry_id


end

app/models/unit.rb
class Unit < ActiveRecord::Base
  # attr_accessible :title, :body
  has_one :entry_ingredient
  
end

app/models/user.rb
class User < ActiveRecord::Base
  #acts_as_authentic
  has_many :entries, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.xml
  # index lists all entries
  def index
    @entries = Entry.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.xml
  
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.xml
  def new
    @entry = Entry.new
    @entry.entry_ingredients.build.build_ingredient
    @entry.steps.build
    
    @ingredient = Ingredient.where(params[:ingredient]).first_or_create()

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
    
    #if no ingredients
    if @entry.ingredients.size == 0
      #build an ingredient
      @entry.entry_ingredients.build.build_ingredient
    #otherwise do nothing
    end
    #same for steps
    if @entry.steps.size == 0
      @entry.steps.build
    end
    
  end

  # POST /entries
  # POST /entries.xml
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to(@entry, :notice => 'Entry was successfully created.') }
        format.xml  { render :xml => @entry, :status => :created, :location => @entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.xml
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to(@entry, :notice => 'Entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.xml
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to(entries_url) }
      format.xml  { head :ok }
    end
  end
  
  def destroy_multiple
    @entries = Entry.destroy(params[:entry_ids])
    
      respond_to do |format|
        format.html { redirect_to(entries_url, :notice => "Successfully deleted #{view_context.pluralize(@entries.count, 'entry')}.") }
        format.json { head :no_content }
      end 

  end
  
  #TODO delete should remove the index from the database and send the entry to trash instead of destroying
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #for setting yes no instead of true false on booleans.  Not using this using, locales instead but I'm keeping this here just as a reference since it was the first helper I wrote :)
  # def yesno(value)
  #   value ? "Yes" : "No"
  # end
  

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_entry_ingredient_fields.html.erb
<li>
	<%= f.fields_for :ingredient do |builder| %>
		<%= builder.label :name %>
		<%= builder.text_field :name, :class => "ingredient_field" %>
	<% end %>
	<%= f.label :quantity %>
	<%= f.text_field :quantity, :class => "ingredient_quantity" %>
	<%= f.label :unit_id, "Unit" %>
	<%= f.select :unit_id, Unit.all.map { |u| [u.name, u.id] }, { :prompt => "Please Select" }, { :class => "ingredient_unit" } %>
	<%= f.hidden_field :_destroy, :class => "delete_ingredient" %>
	<%= link_to "Remove", "#", :class => "remove_fields" %>
</li>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- user_id will be removed from this form when user sessions are implemented-->
  <!-- <div class="field">
    <%= f.label :user_id, "User ID:" %><br />
    <%= f.text_field :user_id %>
  <div> -->
  <div class="field">
    <%= f.label :name, "Name (What are you making?):" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :autolyse %><br />
	<%= f.label :autolyse, "Yes", :value => "true"  %>
    <%= f.radio_button :autolyse, true %>
	<%= f.label :autolyse, "No", :value => "false" %>
	<%= f.radio_button :autolyse, false, :checked => true %>
  </div>
  <div class="field">
    <%= f.label :pre_ferment, "Pre-ferment" %><br />
	<%= label :pre_ferment, "Yes" %>
    <%= f.radio_button :pre_ferment, true %>
	<%= label :pre_ferment, "No" %>
	<%= f.radio_button :pre_ferment, false, :checked => true %>
  </div>

  <div id="ingredients">
	  <p>Ingredient List:</p>
	  <ul id="ingredient_list">
		  <%= f.fields_for :entry_ingredients do |builder| %>
		  <%= render 'entry_ingredient_fields', :f => builder %>
		  <% end %>
	  </ul>
  </div>
  <div id='add_ingredient'>Add Ingredient</div>
  <div id='steps'>
	  <p>Steps:</p>
	  <ol id='step_list'>
		  <%= f.fields_for :steps do |builder| %>
		  <%= render 'step_fields', :f => builder %>
		  <% end %>
	  </ol>
  </div>
  <div id='add_step'>Add Step</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/_step_fields.html.erb
<li>
  <%= f.text_area :description, :cols => 80, :rows => 5, :class => "step_field" %>
  <%= f.hidden_field :_destroy, :class => "delete_step" %>
  <%= link_to "Remove", "#", :class => "remove_fields" %>
</li>

app/views/entries/edit.html.erb
<% @page_title = "Edit Entry"%>
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<% @page_title = "Entries"%>
<h1>Journal Entries</h1>
<% if @entries.blank? %>
	<p>There are no entries yet, start baking and documenting!</p>
<% else %>
	<p>You have <%= pluralize(@entries.count, 'entry') %></p>
	<%= form_tag destroy_multiple_entries_path, :method => :delete do %>
	<table id="entries">
		<tr class="header">
			<th><input type="checkbox" id="checkHead"></th>
			<th>Name</th>
			<th>Grains</th>
			<th>Autolyse</th>
			<th>Pre-Ferment</th>
			<th>Hydration</th>
			<th>Modified</th>
		</tr>
		<tbody>
		<% @entries.each do |e| %>
		<tr class="<%= cycle('odd', 'even')%>">
				<td><%= check_box_tag "entry_ids[]", e.id, false, :class => 'checkTbl' %></td>
				<td><%= link_to(e.name, {:action => 'edit', :id => e.id} ) %></td>
				<td><%= e.grains %></td>
				<td><%= t e.autolyse.class %></td>
				<td><%= t e.pre_ferment.class %></td>
				<td><%= e.hydration %></td>
				<td><%= e.updated_at.strftime('%-m/%-d/%Y') %></td>
			</tr>
		</tbody>
		<% end %>
	</table>
	<%= submit_tag "Delete Selected", { :class => 'delete'} %>
	<% end %>
<% end %>
<div class = "button">
	<p><%= link_to "New Entry", {:action => 'new'}%></p>
</div>
<div id = "note">*For more accurate hydration level and bakers percentages please try to supply mass instead of volume of ingredients (ie. 'grams' instead of 'cups').</div>

app/views/entries/new.html.erb
<% @page_title = "New Entry" %>
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<% @page_title = "#{@entry.name}"%>

<p>
	<b>Created:</b>
	<%= @entry.created_at.strftime('%-m/%-d/%Y') %>
</p>

<p>
  <b>Name:</b>
  <%= @entry.name %>
</p>
<p>
  <b>Autolyse:</b>
  <%= t @entry.autolyse.class %>
</p>
<p>
  <b>Pre-ferment:</b>
  <%= t @entry.pre_ferment.class %>
</p>
<p>
  <b>Ingredients:</b>
  <ol>
	<% for ingredient in @entry.ingredients %>
  	<li>
		<%= ingredient.name %> - 
			<% for portion in ingredient.entry_ingredients %>
				<%= portion.quantity %>
				<%= portion.unit.name %>
			<% end %>
	</li>
	<% end %>
  </ol>
</p>
<p>
  <b>Steps:</b>
  <ol>
	<% for step in @entry.steps %>
  	<li>
		<%= step.description %>
	</li>
	<% end %>
  </ol>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baking Journal - <%= @page_title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p id="error"><%= flash[:error] %></p>
    <% end %>

<%= yield %>

<div id='footer'>&copy;<%= Time.now.year %> Technomad Inc.</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>